try :
    print(x)
except NameError :
    print("변수가 정의되지 않아 오류가 발생함!")
